name: Update pkg info file

on:
  schedule:
    - cron: 0 5 1 * * # every 1st day of the month
  workflow_dispatch:

jobs:
  update-pkg:
    uses: FirelightFlagboy/gh-actions-workflows-docker-services/.github/workflows/update-pkg-info.yml@97790dc4c0cad53e14a08aa4e33c7cd175a4e159
    permissions:
      contents: write
      pull-requests: write
    with:
      pkg-info-path: pkg_info.json
